### ISSUE TITLE
Setup Travis CI

### ISSUE THREAD

**Issue by Atry** [ThoughtWorks-Xi-an-Scala-Camp/scalaz-monad-factory#3]
To enable Travis CI, we need these steps:

1. Create a `.travis` file.
2. Enable the Travis CI hook.
3. Add the status icon to `README.md`.

**Comment by mengmeng0927** [comment]
Done.
https://travis-ci.org/ThoughtWorks-Xi-an-Scala-Camp/scalaz-monad-factory

**Comment by Atry** [comment]
Congratulation!
